# Generated by Django 2.2.7 on 2019-11-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuti', '0002_auto_20191116_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='id',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='no_surat',
            field=models.TextField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
